foreground      #16191d
background      #dee2e4
selection_foreground #16191d
selection_background #a7c2e0
url_color       #45688d
cursor          #2e3439
cursor_text_color #e3e8ea
active_border_color   #b08618
inactive_border_color #aab3ba
active_tab_background   #c4cdd3
active_tab_foreground   #2e3439
active_tab_font_style   bold
inactive_tab_background #dee2e4
inactive_tab_foreground #4e565c
color0  #2e3439
color1  #a3412f
color2  #3a703f
color3  #8a6417
color4  #2f63b0
color5  #7b48c4
color6  #2f7575
color7  #d0d6d9
color8  #525a60
color9  #a85c46
color10 #6c8c68
color11 #a37c2e
color12 #5a80a8
color13 #9a64a3
color14 #4f8485
color15 #f2f4f5
color185 #9c8417
