config_version = 13

[bar.main]
enabled = true
layer = "top"
position = "top"

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = false

[keybinds]
down = [ "Down", "Tab" ]
up = [ "Up", "Shift+ISO_Left_Tab" ]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 518.5
    output = "eDP-2"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
layer = "overlay"

[shell]
app_icon_colorize = false
lang = ""

    [shell.launcher]
    app_grid = false
    categories = false
    compact = false
    show_icons = true

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    control_center_placement = "attached"
    floating_offset = 8
    open_near_click_control_center = false
    open_near_click_wallpaper = false
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = false

    [shell.screenshot]
    directory = "/home/XXiaoA/Pictures/Screenshots"

[theme]
builtin = "Tokyo-Night"
community_palette = "Atuel"
mode = "light"
pure_black_dark = false
source = "builtin"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = []

[wallpaper]
fill_mode = "crop"

    [wallpaper.default]
    path = "/home/XXiaoA/Pictures/Wallpapers/ign-waifu.png"

    [wallpaper.last]
    path = "/home/XXiaoA/Pictures/Wallpapers/ign-waifu.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/XXiaoA/Pictures/Wallpapers/ign-waifu.png"

    [wallpaper.monitors.eDP-2]
    path = "/home/XXiaoA/Pictures/Wallpapers/ign-waifu.png"