#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color "#e67e80"
bspc config normal_border_color  "#2f343f"
bspc config active_border_color  "#2f343f"
bspc config presel_feedback_color "#e67e80"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Chrome desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating


feh --bg-scale $HOME/Pictures/image_2022-08-26_22-29-50.png
keymapper &
dunst &
picom -b & 
fcitx5 &
$HOME/.config/polybar/launch.sh
