#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color "#78a3e2"
bspc config normal_border_color "#282a36"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating


feh --bg-fill $HOME/Pictures/wallpaper/焦茶_71295163_浅瀬0.jpg
# feh --randomize --bg-fill ~/Pictures/wallpaper/*
xsetroot -cursor_name left_ptr
keymapper &
dunst &
$HOME/.config/polybar/launch.sh
nm-applet &
picom -b --experimental-backends &
fcitx5 &
udiskie &
