#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 # 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config focused_border_color "#56949f"
bspc config normal_border_color "#908caa"
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a discord desktop='^2'
bspc rule -a steam desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a imv state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above


~/.fehbg
# feh --randomize --bg-fill ~/Pictures/wallpaper/*
xsetroot -cursor_name left_ptr
keymapper &
dunst &
picom -b &
fcitx5 &
udiskie &

# lauch bar
eww daemon
rm /tmp/eww_bar.lock
~/dotfiles/eww/toggle_bar

~/dotfiles/scripts/fullscreen &
