#!/bin/bash

exec 9>/tmp/fullscreen.lock
if ! flock -n 9; then
    printf 'another instance is running\n';
    exit 1
fi

# node_remove is used for telgram only
bspc subscribe node_state node_remove| while read -r event _ _ node_id state flag; do
    if [ ! -f "/tmp/eww_bar.lock" ]; then
        continue
    fi

    if [ "$event" == "node_remove" ]; then
        class_name=$(bspc query -T -n | rg -o 'className":"(.*?)",' | sed 's/className":"//;s/",//')
        if [ "$class_name" == "TelegramDesktop" ]; then
            eww open bar
            echo "TG"
        fi
    elif [ "$event" == "node_state" ]; then
        if [ "$state" != "fullscreen" ]; then
            continue
        fi
        if [ "$flag" == on ]; then
            eww close-all
        else
            eww open bar
        fi
    fi
done
