[colors]
ansi = [
	'#414b50',
	'#e67e80',
	'#a7c080',
	'#dbbc7f',
	'#7fbbb3',
	'#d699b6',
	'#83c092',
	'#d3c6aa',
]
background = '#272e33'
brights = [
	'#475258',
	'#e67e80',
	'#a7c080',
	'#dbbc7f',
	'#7fbbb3',
	'#d699b6',
	'#83c092',
	'#d3c6aa',
]
cursor_bg = '#d3c6aa'
cursor_border = '#d3c6aa'
cursor_fg = '#272e33'
foreground = '#d3c6aa'

[colors.indexed]

[metadata]
name = 'Everforest'
origin_url = 'https://github.com/frdwin/Everforest-Wezterm'
