[metadata]
name = "Rosé Pine Moon"
author = "XXiaoA"

[colors]
foreground = '#e0def4'
background = '#232136'
cursor_bg = '#ea9a97'
cursor_border = '#ea9a97'
cursor_fg = '#2a273f'
selection_bg = '#393552'
selection_fg = '#e0def4'

ansi = [ '#393552', '#eb6f92', '#3e8fb0', '#f6c177', '#9ccfd8', '#c4a7e7', '#ebbcba', '#e0def4' ]
brights = [ '#817c9c', '#eb6f92', '#3e8fb0', '#f6c177', '#9ccfd8', '#c4a7e7', '#ebbcba', '#e0def4' ]
